# scwhine-proton — GE-Proton10-34 + winewayland.drv / wineserver patches
#
# Strategy:
#   Build wine from nixpkgs (staging, WoW64) with our two patches applied.
#   Combine the resulting unix-side wine tree with GE-Proton10-34's binary
#   components (DXVK, VKD3D-Proton, Proton scripts, mono, gecko) which are
#   Windows PE DLLs and do not depend on SERVER_PROTOCOL_VERSION.
#
# The resulting compat tool is installed alongside the upstream GE-Proton10-34
# so both remain selectable in Steam.  battlenet.nix targets this tool.
{ stdenv
, pkgs
, fetchurl
, autoPatchelfHook
, makeWrapper
, unzip
, rsync
}:

let
  toolVersion = "GE-Proton10-34";
  toolName    = "scwhine-${toolVersion}";

  # ── GE-Proton10-34 binary (for DXVK, VKD3D, scripts, mono, gecko) ────────
  ge-proton-src = fetchurl {
    url  = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/${toolVersion}/${toolVersion}.tar.gz";
    hash = "sha256-lzPsYYcrp5NoT3B0WFj3o10Z7tXx7xva1wEP3edeuqM=";
  };

  # ── Patched wine (nixpkgs staging WoW64 + our two scwhine patches) ────────
  #
  # nixpkgs.wineWowPackages.staging ships wine + wine-staging, built with
  # WoW64 (32+64-bit).  We apply our patches on top.
  #
  # Our patches touch:
  #   dlls/winewayland.drv/   — pUpdateLayeredWindow, ARGB layered surfaces,
  #                             zwp_linux_dmabuf_v1 binding, EGL dmabuf IPC,
  #                             SNI StatusNotifierItem systray
  #   server/                 — share_dmabuf_fd / get_dmabuf_fd protocol entries
  #   include/wine/server_protocol.h  (regenerated by make_requests)
  # wineWow64Packages is the non-deprecated successor to wineWowPackages.
  wine-scwhine = pkgs.wineWow64Packages.staging.overrideAttrs (old: {
    pname = "wine-scwhine";

    # wine-staging patches are already baked in by the nixpkgs staging
    # variant; only add our winewayland / wineserver patches on top.
    # Patch 0002 includes the linux-dmabuf XML as a new file, so no
    # separate postPatch step is needed to inject it.
    patches = (old.patches or []) ++ [
      # Patch 1: implement pUpdateLayeredWindow so layered windows commit to wl_surface
      ./patches/0001-winewayland-implement-pUpdateLayeredWindow.patch
      # Patch 2: replace blocking second roundtrip in wayland_process_init — fixes
      # the Battle.net freeze/grey-window caused by the CEF renderer+GPU subprocess
      # deadlocking on a Wayland roundtrip while the browser's IPC times out
      ./patches/0002-winewayland-replace-second-blocking-roundtrip-with-n.patch
      # Patch 3: commit stored layered-window pixels after xdg_surface configure —
      # fixes permanently blank CEF windows that call UpdateLayeredWindow before
      # their first compositor configure event arrives
      ./patches/0003-winewayland-commit-stored-layered-window-pixels-afte.patch
      # Patch 4: SNI StatusNotifierItem systray — tray icon integration for
      # KDE Plasma 6, GNOME+AppIndicator, Waybar; no XWayland needed
      ./patches/0004-winewayland-add-SNI-StatusNotifierItem-systray-pSyst.patch
    ];

    # Patch 4 needs libdbus for org.kde.StatusNotifierItem
    buildInputs = (old.buildInputs or []) ++ [ pkgs.dbus ];

  });

  # ── Final compat tool ─────────────────────────────────────────────────────
in stdenv.mkDerivation {
  pname   = toolName;
  version = toolVersion;
  src     = ge-proton-src;

  nativeBuildInputs = [ autoPatchelfHook makeWrapper rsync unzip ];

  # No normal configure/build; we assemble from pre-built parts.
  dontConfigure = true;
  dontBuild     = true;

  installPhase = ''
    runHook preInstall

    local dest="$out/${toolName}"
    mkdir -p "$dest"

    # 1. Unpack the GE-Proton binary as the base (DXVK, VKD3D, scripts, etc.)
    cp -r . "$dest/"

    # 2. Replace wine's unix-side DLLs and wineserver with our patched build.
    #    All files sharing SERVER_PROTOCOL_VERSION must come from the same build.
    rsync -a --delete \
      "${wine-scwhine}/lib/wine/x86_64-unix/" \
      "$dest/files/lib/wine/x86_64-unix/"

    # 32-bit (WoW64) unix DLLs
    [ -d "${wine-scwhine}/lib/wine/i386-unix" ] && \
      rsync -a --delete \
        "${wine-scwhine}/lib/wine/i386-unix/" \
        "$dest/files/lib/wine/i386-unix/" || true

    # Wine PE (Windows-format) DLLs — replace these too so client-side wine
    # code matches the wineserver protocol (built together, same version).
    rsync -a --delete \
      "${wine-scwhine}/lib/wine/x86_64-windows/" \
      "$dest/files/lib/wine/x86_64-windows/" || true
    [ -d "${wine-scwhine}/lib/wine/i386-windows" ] && \
      rsync -a --delete \
        "${wine-scwhine}/lib/wine/i386-windows/" \
        "$dest/files/lib/wine/i386-windows/" || true

    # wineserver binary
    install -Dm 0755 "${wine-scwhine}/bin/wineserver" \
      "$dest/files/bin/wineserver"

    # wine loader
    for bin in wine wine64 wine-preloader; do
      [ -f "${wine-scwhine}/bin/$bin" ] && \
        install -Dm 0755 "${wine-scwhine}/bin/$bin" "$dest/files/bin/$bin" || true
    done

    # 3. DXVK, VKD3D-Proton, mono, gecko from GE-Proton stay untouched
    #    (they are Windows PE DLLs; SERVER_PROTOCOL_VERSION is irrelevant).

    # 4. Compat tool metadata
    cat > "$dest/compatibilitytool.vdf" <<EOF
"compatibilitytools"
{
  "${toolName}"
  {
    "install_path" "."
    "display_name" "scwhine GE-Proton10-34 (Wayland/SNI)"
    "from_oslist"  "windows"
    "to_oslist"    "linux"
  }
}
EOF

    cat > "$dest/toolmanifest.vdf" <<EOF
"manifest"
{
  "version"     "2"
  "commandline" "/proton %verb%"
  "require_tool_appid" "1628350"
  "use_sessions" "1"
  "compatmanager_layer_name" "proton"
}
EOF

    runHook postInstall
  '';

  meta = {
    description = "GE-Proton10-34 with Wayland layered-window, dmabuf IPC, and SNI systray fixes";
    homepage    = "https://github.com/GloriousEggRoll/proton-ge-custom";
    platforms   = [ "x86_64-linux" ];
  };
}
